### ISSUE TITLE
New Domain(s)

### ISSUE THREAD

**Issue by xdisplay** [nikolaischunk/discord-phishing-links#138]
discordrpp.com
disocrds.gift
e-giftpremium.com
discorld.ru

**Comment by NanduWasTaken** [comment]
Could you just have a PR req?

**Comment by NanduWasTaken** [comment]
> discordrpp.com disocrds.gift e-giftpremium.com discorld.ru

👌

**Comment by xdisplay** [comment]
I have, they weren't a thing before
