### ISSUE TITLE
False Positive - Steam Community

### ISSUE THREAD

**Issue by QwaserLi** [nikolaischunk/discord-phishing-links#156]
`steamcommunity.com` appears in the domain list but is this not the Official URL for the Steam Community Page?

If you go to your Steam Application and Go the Community Tab, Right-Clicking anywhere on the page and clicking _Copy Page URL_ gives the `https://steamcommunity.com/home` URL

![image](https://user-images.githubusercontent.com/40726675/154221720-bc3dd6df-d704-47fb-a4ee-471b8edcbcde.png)

**Comment by SkyDiscovery** [comment]
> `steamcommunity.com` appears in the domain list but is this not the Official URL for the Steam Community Page?

@QwaserLi, Please link where you found it in the list.

**Comment by QwaserLi** [comment]
No problem Line 6247 on https://github.com/nikolaischunk/discord-phishing-links/blob/main/domain-list.json

**Comment by lucapolesel** [comment]
@QwaserLi It is actually using `ì` and not an `i`.
Are you using the npm package? If so which version?

**Comment by QwaserLi** [comment]
All sorted now guys. @lucapolesel Thanks!
