### ISSUE TITLE
Domains with unicode characters

### ISSUE THREAD

**Issue by lucapolesel** [nikolaischunk/discord-phishing-links#160]
@SkyDiscovery I've noticed the other day that with the PR #150 you introduced three domains with unicode characters.
I did convert those characters but I would like to ask you to review them and see if they are still correct.

| Old domain                    | New domain           | Fixed Domain |
|-------------------------------|---------------------|---------------------
| steamcommun\u00c3\u00acty.com | steamcommunÃ¬ty.com | steamcommunìty.com |
| disc\u00c3\u00b6rd.com        | discÃ¶rd.com        | discörd.com |
| dis\u00c3\u00a7ordapp.com     | disÃ§ordapp.com     | disçordapp.com |

**Comment by lucapolesel** [comment]
I figured it out and fixed them with this module https://github.com/rspeer/python-ftfy
I'll create a new PR.

**Comment by SkyDiscovery** [comment]
Thank you, @lucapolesel!
I guess they broke in some sorting process and I didn't noticed it…
