### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by ProbablyRaging** [nikolaischunk/discord-phishing-links#183]
As Discord uses the `discord.gg` domain for certain things like server/game invites, this one causes some false positives

https://github.com/nikolaischunk/discord-phishing-links/blob/26cbac7c02e827bb1a1a37a221449ecea6e2b332/domain-list.json#L4826

**Comment by lucapolesel** [comment]
@ProbablyRaging Are you using the npm package? If so please check that you are using a new version `>= 0.2.0`.
The false positive isn't caused by the list but by the check that the module made pre-version `0.2.0`.
Let me know.
Thank you

**Comment by nikolaischunk** [comment]
@lucapolesel this also brings up the question if we should include the two other domains again? yk `iscord.gg`

**Comment by lucapolesel** [comment]
@nikolaischunk yeah, I think that we should put some kind of message on top of the readme like "If false positive please make suere you are using version.." or so. But let's see if it was indeed using an older version first.

**Comment by lucapolesel** [comment]
@nikolaischunk @ProbablyRaging From what I can see (I might be wrong) if you are refering to your bot `CreatorBot` it seems like you are not using the module but your own implementation based on the old npm package's code.
See: https://github.com/ProbablyRaging/CreatorBot/blob/master/modules/blacklist/bl_nitro.js#L34
That `.includes(..)` is causing false positives.

**Comment by ProbablyRaging** [comment]
@lucapolesel correct, I'm just fetching the json file from this repo and doing my own check against it (not a very good one). I appreciate the info and will start using the npm package ASAP.

Also, a link for you to add is `discrdgifts.com/event`, let me know if you'd like me to create a new issue for this.
