### ISSUE TITLE
New scam I just found

### ISSUE THREAD

**Issue by adri326** [nikolaischunk/discord-phishing-links#199]
The game pretends to be "the new best adventure game", but it was advertised through a token-grabbed discord account. The website is a collection of stolen assets from the upcoming game "Silt" and it downloads a file called "SpiralCircus.rar"; I didn't dare downloading it. I had a fun time forcing the hacker to speak french to me.

```
spiralcircus.org
bit.ly/spiralcircus
```

**Comment by nikolaischunk** [comment]
Added in #200 ;) ty!
