### ISSUE TITLE
I dont know how to use this, could someone give me a small guide

### ISSUE THREAD

**Issue by Ymez1** [nikolaischunk/discord-phishing-links#239]

**Comment by nikolaischunk** [comment]
hey, happy to help you out. What exactly do you not understand? 
This repository is a collection of phishing links. not much to do with it. 
there is a npm package that works with this repo if you are looking for this.
[stop-discord-phishing](https://www.npmjs.com/package/stop-discord-phishing)

**Comment by nikolaischunk** [comment]
@Ymez1

**Comment by nikolaischunk** [comment]
Please reopen if your really interested in responding an getting an answer :)
