### ISSUE TITLE
False suspicious link

### ISSUE THREAD

**Issue by A-Beille** [nikolaischunk/discord-phishing-links#277]
Hello, in the list of all suspicious links, I saw a link named "any.run", but I know this URL: this website is to analysis files in onlines virtuals machines. I use it often.

**Comment by nikolaischunk** [comment]
checking :)

**Comment by nikolaischunk** [comment]
![grafik](https://user-images.githubusercontent.com/58025175/172060949-d9147783-e0cb-40c8-9413-de64ca280bd6.png)
you are absolutely correct, will get removed.
