### ISSUE TITLE
Potentially false positive

### ISSUE THREAD

**Issue by A-Beille** [nikolaischunk/discord-phishing-links#308]
The link "discord.gift" is the default link for gifts in discord, like discord.com/gift

**Comment by nikolaischunk** [comment]
hey :) I checked the code, and there seems not to be a single link matching exact `discord.gift`.
Could you provide me the line where you found the domain?

**Comment by A-Beille** [comment]
Even I don't know where I found it... It seems like it was an error. Sorry !
