### ISSUE TITLE
New domains and URLs

### ISSUE THREAD

**Issue by NotByMe** [nikolaischunk/discord-phishing-links#313]
This specific URL https://steam-airdrops.com/air and it opens the "nitro" page; the original domain, https://steam-airdrops.com however returns a 404 error as "the file does not exist" :/ Though I think both are worthy to be put on the list.

**Comment by NotByMe** [comment]
Another one: https://clck.ru/resR6

**Comment by nikolaischunk** [comment]
Done :) ty both
