### ISSUE TITLE
New link i guess

### ISSUE THREAD

**Issue by rbunpat** [nikolaischunk/discord-phishing-links#326]
not sure if this link applies but here
link(dash)hub(dot)net

**Comment by nikolaischunk** [comment]
can you show proof of that link beeing used as scam?

**Comment by rbunpat** [comment]
> can you show proof of that link beeing used as scam?

uh I didn't capture my screen but the link says something about a** and p*** or something like that. Also the same user sent an nsfw discord server invite(pretty sure it's a verification qr code scam) in a tech discord. You can close the issue, i'm just not sure if the link was scam lol.
