### ISSUE TITLE
CDN Link getting detected

### ISSUE THREAD

**Issue by Pukimaa** [nikolaischunk/discord-phishing-links#410]
When using this link: https://cdn.discordapp.com/emojis/829306161424498688.gif?size=48&quality=lossless&size=40
It'll be marked as malicious. Even though this is clearly an official Discord URL.

**Comment by Pukimaa** [comment]
Most likely "discordapp.com" gets detected

**Comment by Pukimaa** [comment]
I saw the problem was discordapp.co

**Comment by Pukimaa** [comment]
Ok this happens to me just because of my python code checking if it *contains* it. A python library would be beneficial.

**Comment by nikolaischunk** [comment]
Hi @Pukimaa thanks for your Issue!
There is a NPM Package to work with this List, you can find it at [stop-discord-pishing](https://github.com/nikolaischunk/stop-discord-phishing). Take a look at how we detect links with a regex there, you maybe be able to recreate the detection in python :)
