### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by jhonseaner** [nikolaischunk/discord-phishing-links#462]
We're do I get the actual information please

**Comment by nikolaischunk** [comment]
Hi! Please specify, what you mean by this?
`discord-phishing-links` is just a collection of links.

**Comment by jhonseaner** [comment]
> Hi! Please specify, what you mean by this?
> 
> `discord-phishing-links` is just a collection of links.

Does it not grab the information for you

**Comment by nikolaischunk** [comment]
As stated. This is only a collection, not a verifier of some kind.
