### ISSUE TITLE
API with over 6555+ domains - Collab??

### ISSUE THREAD

**Issue by BlackWolfWoof** [nikolaischunk/discord-phishing-links#65]
Hello there 👋, I am helping out with a few people to take down those phishing domains and we have created an API which currently gets around 10-20 new domains per day and is always up to date. 
I'll merge all new domains I can find here into our API.

If you are interested in collaborating, I could get some contributors and the repo owner into the server which is used to add the domains to our API and to talk about phishing.
Currently Discord bots like Dyno, [Fish](https://github.com/Benricheson101/anti-phishing-bot) (open source) and a few others are using our API.

**Comment by nikolaischunk** [comment]
Hey BlackWolfWoof, is this API you are talking about on Github? If yes, please send the Github Repository in a Comment :)
I'm courious about that API Concept, could you elaborate what exactly you have in mind when your talking about a collaboration?
Thankyou!

**Comment by BlackWolfWoof** [comment]
Nope, it is not hosted on GitHub. 
We should move our conversation to Discord DM's if that is fine with you. 
You can friend request me `Black Wolf#0001` and if you didn't already, link your GitHub account to Discord, so i know it is you. 
Also you might wanna tell me your username too, because i got a bunch of friend requests and it'll be difficult to find you 😅

**Comment by nikolaischunk** [comment]
Done, it's Chillihero#0001
