### ISSUE TITLE
Update the domains

### ISSUE THREAD

**Issue by HARDYSLICE** [nikolaischunk/discord-phishing-links#92]
There are new scam links. Update them from https://github.com/DevSpen/scam-links/blob/master/src/links.txt

**Comment by nikolaischunk** [comment]
Hey @HARDYSLICE this repository contains all kind of scam links not only discord related ones. So just "integrating" them in here will not be possible. If you have specific discord scam links from there that are not included here yet, feel free to contribute them!

**Comment by nikolaischunk** [comment]
I picked out the discord & steam related scamdomains and added them https://github.com/nikolaischunk/discord-phishing-links/pull/93
