### ISSUE TITLE
discordapp.com flagged as malicious [false positive]

### ISSUE THREAD

**Issue by adri326** [nikolaischunk/discord-phishing-links#94]
This time it's `"discordapp.co"` ([Line 1277](https://github.com/nikolaischunk/discord-phishing-links/blob/main/domain-list.json#L1277)) that matches part of the url. You might want to use some regex to extract the URLs and match the entirety of the URL

**Comment by nikolaischunk** [comment]
I see. 
will remove the domain. I currently can't think of a solution that works for all the domains, my current regex skills are not that good sadly
